name: Lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read
  checks: write

jobs:
  run-linters:
    name: Run dotnet format on changed files
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"

      - name: Detect changed C# files
        id: detect-changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }}
            FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep '\.cs$' || true)
          else
            FILES=$(git diff --name-only HEAD^ | grep '\.cs$' || true)
          fi

          echo "Changed files:"
          echo "$FILES"

          echo "CHANGED_FILES=$FILES" >> $GITHUB_ENV
          echo "::set-output name=changed::$FILES"

      - name: Run dotnet format on changed files
        if: steps.detect-changes.outputs.changed != ''
        run: |
          echo "Formatting: $CHANGED_FILES"
          dotnet format --include $CHANGED_FILES --folder || echo "::warning::Formatting issues fixed."

      - name: Commit fixes (if any)
        if: steps.detect-changes.outputs.changed != ''
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "fix: auto-format C# files via dotnet format"
            git push
          fi
