name: Main Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: write
  checks: write

jobs:
  lint:
    uses: ./.github/workflows/pipe-lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/pipe-build.yml
    
  leaks:
    needs: build
    uses: ./.github/workflows/pipe-scan-leaks.yml
    secrets: inherit
    
  sonar:
    needs: leaks
    uses: ./.github/workflows/pipe-sonar.yml
    secrets: inherit
    
  test:
    needs: leaks
    uses: ./.github/workflows/pipe-test.yml
