name: Pipeline for Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js (latest stable version)
        uses: actions/setup-node@v2
        with:
          node-version: '21' 

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
