name: DCA

on:
  push:
    branches:
      - feature/issue-26  
  pull_request:
    branches:
      - main  

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://vs-gate.dei.isep.ipp.pt:10531'
          cmd_options: '-config api.disablekey=true'
          docker_image: 'owasp/zap2docker-stable:2.10.0'