name: Pipeline for Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Get modified files
        id: files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.cs$' > changed_files.txt
          cat changed_files.txt

      - name: Run linting and format on modified files
        run: |
          if [ -s changed_files.txt ]; then
            dotnet format $(cat changed_files.txt) 
          else
            echo "No C# files modified"
          fi
