name: Scan Leaks

on:
  workflow_call:

permissions:
  contents: write
  checks: write

jobs:
  scan_leaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}