name: Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: write
  checks: write

jobs:
  run-dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"

      - name: Get changed C# files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep '\.cs$' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run dotnet format on changed files
        if: env.CHANGED_FILES != ''
        run: |
          echo "Formatting changed files: $CHANGED_FILES"
          dotnet format --include $CHANGED_FILES --folder --verify-no-changes || echo "::warning::Formatting issues fixed."

      - name: Commit changes
        if: env.CHANGED_FILES != '' && steps.changed-files.outcome == 'success'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $CHANGED_FILES
          git commit -m "fix: auto-fix formatting issues [dotnet format]" || echo "No changes to commit"
          git push
