name: Pipeline for Lint

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

permissions:
  contents: read
  checks: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      cs_files: ${{ steps.filter.outputs.cs }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cs:
              - '**/*.cs'

  run-lint:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.cs_files != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Run dotnet format only on changed files
        run: |
          echo "Changed files:"
          echo "${{ needs.detect-changes.outputs.cs_files }}"
          
          dotnet format ./ShopTex.sln --include ${{ needs.detect-changes.outputs.cs_files }} --verify-no-changes --verbosity diagnostic
