name: DCA

on:
  push:
    branches:
      - feature/issue-26
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan each API endpoint individually
    strategy:
      matrix:
        endpoint:
          - /api/auth/signin
          - /api/auth/signup
          - /api/auth/me
    steps:
      - name: Set target URL
        id: set_target_url
        run: echo "BASE_URL=https://vs-gate.dei.isep.ipp.pt:10531" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Health Check (${BASE_URL}${{ matrix.endpoint }})
        run: |
          echo "Checking ${{ env.BASE_URL }}${{ matrix.endpoint }}"
          RESPONSE=$(curl -k --write-out "%{http_code}" --silent --output /dev/null ${{ env.BASE_URL }}${{ matrix.endpoint }})
          if [ "$RESPONSE" -eq 000 ]; then
            echo "::error::Health check failed (no response)"
          else
            echo "Health check passed (HTTP $RESPONSE)"
          fi

      - name: ZAP Full Scan on ${{ matrix.endpoint }}
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.BASE_URL }}${{ matrix.endpoint }}
          cmd_options: '-a'
