name: DCA

on:
  push:
    branches:
      - feature/issue-26
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Set target URL
        id: set_target_url
        run: echo "TARGET_URL=https://vs-gate.dei.isep.ipp.pt:10531" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Health Check (apenas verifica se está online)
        run: |
          echo "Performing health check..."
          RESPONSE=$(curl -k --write-out "%{http_code}" --silent --output /dev/null ${{ env.TARGET_URL }})
          echo "Status: $RESPONSE"
          if [ "$RESPONSE" -eq 000 ]; then
            echo "Health check falhou: sem resposta do servidor"
            exit 1
          else
            echo "Servidor está online (HTTP $RESPONSE)"
          fi

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.TARGET_URL }}
          cmd_options: '-a'
