name: Pipeline for Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
  checks: write
  
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      cs_files: ${{ steps.filter.outputs.cs_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed C# files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            cs_files:
              - '**/*.cs'

  lint-changed-files:
    needs: detect-changes
    if: needs.detect-changes.outputs.cs_files != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"

      - name: Run dotnet format only on changed files
        run: |
          echo "Changed C# files:"
          echo "${{ needs.detect-changes.outputs.cs_files }}"

          # Convert to space-separated list
          FILES=$(echo "${{ needs.detect-changes.outputs.cs_files }}" | jq -r '.[]' | tr '\n' ' ')
          
          # Run format only on changed files
          dotnet format ./ShopTex.sln --include $FILES --verify-no-changes --verbosity diagnostic