name: Lint changed files

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
  checks: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      cs_changed: ${{ steps.filter.outputs.cs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            cs:
              - '**/*.cs'

  lint-changed-files:
    needs: detect-changes
    if: needs.detect-changes.outputs.cs_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"

      - name: Run dotnet format only if C# files changed
        run: |
          echo "C# files changed. Running dotnet format."
          dotnet format ./ShopTex.sln --verify-no-changes --verbosity diagnostic
