name: DCA

on:
  push:
    branches:
      - feature/issue-26
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run Full ZAP Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://vs-gate.dei.isep.ipp.pt:10531'
          cmd_options: '-a'