name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release