name: DCA

on:
  push:
    branches:
      - feature/issue-26
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ${{ matrix.endpoint }}
    strategy:
      matrix:
        endpoint:
          - /api/auth/signin
          - /api/auth/signup
          - /api/auth/me

    steps:
      - name: Set base and ping URLs
        run: |
          echo "BASE_URL=https://vs-gate.dei.isep.ipp.pt:10531" >> $GITHUB_ENV
          echo "PING_URL=https://vs-gate.dei.isep.ipp.pt:10531/api/ping" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Health Check (/api/ping)
        if: matrix.endpoint == '/api/auth/signin'
        run: |
          echo "Checking if application is online (/api/ping)..."
          RESPONSE=$(curl -k --write-out "%{http_code}" --silent --output /dev/null "$PING_URL")
          echo "Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ]; then
            echo "::error::Health check failed: /api/ping returned $RESPONSE"
          else
            echo "Application is online (HTTP $RESPONSE)"
          fi

      - name: ZAP Full Scan on ${{ matrix.endpoint }}
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.BASE_URL }}${{ matrix.endpoint }}
          cmd_options: '-a'
          allow_issue_writing: true
          artifact_name: zap_scan_${{ matrix.endpoint }}
