name: DCA

on:
  push:
    branches:
      - feature/issue-26
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Set target URL
        id: set_target_url
        run: echo "TARGET_URL=https://vs-gate.dei.isep.ipp.pt:10531" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Health Check
        run: |
          echo "Performing health check on /api/ping..."
          RESPONSE=$(curl -k --write-out "%{http_code}" --silent --output /dev/null ${{ env.TARGET_URL }}/api/ping)
          echo "Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Health check failed"
          else
            echo "Health check passed (HTTP $RESPONSE)"
          fi

      - name: Provide API Endpoints to ZAP
        run: |
          echo "https://vs-gate.dei.isep.ipp.pt:10531/api/auth/signin" >> urls.txt
          echo "https://vs-gate.dei.isep.ipp.pt:10531/api/auth/signup" >> urls.txt
          echo "https://vs-gate.dei.isep.ipp.pt:10531/api/auth/me" >> urls.txt
    
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.TARGET_URL }}
          urls: urls.txt
          cmd_options: '-a'
