name: Test Pipeline Recognition

on:
  push:
    branches:
      - issue_12
  pull_request:

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "✅ GitHub Actions is recognizing this pipeline!"
